### ISSUE TITLE
Preview

### ISSUE THREAD

**Issue by sitilge** [DaavisGit/image_tshirt#1]
Is there a live preview available?

**Comment by DaavisGit** [comment]
Nope.. don't have any hosting for it

**Comment by sitilge** [comment]
Hmm, afaik, you are running on hostinger.lv :)

**Comment by DaavisGit** [comment]
True, but there is no SSH access so I need to donate more time to this. Maybe soon

**Comment by DaavisGit** [comment]
So. I have placed it on peachyz.xyz.. Handle with care.. the hosting is free and very slow

**Comment by sitilge** [comment]
@DaavisGit  oh, Davis, will try to be gentle :8ball:
